name: Django Test

on:
  pull_request:
    branches:
      - main

env:
  ALLOWED_HOSTS: "localhost,127.0.0.1"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install the project.
        run: uv sync

      - name: Collect Static
        run: |
          uv run manage.py collectstatic --no-input

      - name: Run Tests
        run: |
          uv run pytest
